### ISSUE TITLE
Apply Random Forest to the Car Evaluation Dataset

### ISSUE THREAD

**Issue by AmanPriyanshu** [AmanPriyanshu/DWDM-Project#1]
Apply Random Forest to UCI's Car Evaluation Dataset: https://archive.ics.uci.edu/ml/datasets/car+evaluation

**Comment by prajwal-144** [comment]
Hey, I would like to work on this issue. Can you assign it to me?

**Comment by PSY27** [comment]
I would like to work on this issue

**Comment by PSY27** [comment]
raised a pull request for the same #2
